### ISSUE TITLE
Translation of LLVM IR to Egg expressions

### ISSUE THREAD

**Issue by JonathanDLTran** [cucapra/diospyros#112]
The current translation fails to take into account all possible patterns that LLVM IR can be input, because it only scans for certain patterns in the IR. For instance, if the IR looks like `%11 = fadd %10 %9; %12 = fadd %11 %9`, then current translation fails because a child of `%12` is itself a binary operator. A new solution will translate each IR subexpression recursively, independently of its parent IR node and its child nodes.

**Comment by sampsyo** [comment]
This sounds great!! Happy to chat about design choices to make this work if you're interested.

**Comment by avanhatt** [comment]
To my understanding this has been resolved.
