### ISSUE TITLE
Timeout for translation validation in synth.rkt

### ISSUE THREAD

**Issue by avanhatt** [cucapra/diospyros#24]
Would make sense to throw in timing data per query here, too.

**Comment by rachitnigam** [comment]
Can you clarify what this means? I don't quite follow what "throw in timing data" means.

**Comment by avanhatt** [comment]
I meant including in this commit writing out timing data per query either to a file (not just stdout) or annotating it on a produced file.

**Comment by avanhatt** [comment]
No longer needed; translation validation is not a bottleneck
