### ISSUE TITLE
Aligned writes into output matrix

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/diospyros#3]
Instead of using `vector-shuffle-set!` to set the computation on the output array, create a sketch where the write is done at locations `$i`, `$i+1`, ... and so on.

This forces the sketch to never shuffle the output.

**Comment by rachitnigam** [comment]
Hm, I realize now that if such a solution exists, the program cost minimization procedure will already find it.

**Comment by avanhatt** [comment]
It's feasible that a solution that does this doesn't exist without more iterations/shuffles in the input matrices, right?

**Comment by rachitnigam** [comment]
Right, but wouldn't that also always increase the program cost and therefore not be worth it?

**Comment by rachitnigam** [comment]
It does find a solution when the number of iterations = 6.
