### ISSUE TITLE
raco pkg install c possibly missing from setup

### ISSUE THREAD

**Issue by agent-lee** [cucapra/diospyros#49]
Repro:
- Setup as according to README
- cdios demo/matrix-multiply.c

Throws:
standard-module-name-resolver: collection not found
  for module path: c
  collection: "c"
  in collection directories:
   /home/vtlee/.racket/7.3/collects
   /usr/local/share/racket/collects
   ... [171 additional linked and package directories]

Fixed it with:
raco pkg install c-utils

**Comment by avanhatt** [comment]
Added c-utils instructions in 5e93afb2b5a2763270afb2362c1a2d77481b3904, thanks!!
