### ISSUE TITLE
Need control over emitted kernel function name

### ISSUE THREAD

**Issue by agent-lee** [cucapra/diospyros#57]
Need control over the code generated kernel function name to facilitate integration. Currently the tool defaults to void kernel(<args>) in the generated file. For automation flows, this will eventually need to be supplied by the user so that it can be changed to something arbitrary to eliminate manually copying and adjusting the function call.

This probably will need us to plumb through arguments to the tool to propagate it through to the code generator.

**Comment by avanhatt** [comment]
Agreed! We should also probably default to the function name provided with `cdios` instead of just `kernel` if not otherwise provided.
