### ISSUE TITLE
Control namespace for generated kernels

### ISSUE THREAD

**Issue by agent-lee** [cucapra/diospyros#59]
Generated kernels should probably be encapsulated in a namespace to avoid polluting the base namespace and so that we can precisely call different implementations with potentially the same function call for testing. Probably can get away with a default namespace like dios or diospyros for now but to facilitate automation we may want to allow it to eventually be user controlled since we'll be generating override kernels.

For instance, we may need to call:
// base definition
Eigen::foo(<args>)
// our optimized override
OurNamespace::Eigen::foo(<args>)

**Comment by avanhatt** [comment]
`diospyros` namespace added in https://github.com/cucapra/diospyros/commit/44565c82728503f9f59b47065269f9d9a01e3aad
