### ISSUE TITLE
scalars.h emitted as relative path breaks self-contained build

### ISSUE THREAD

**Issue by agent-lee** [cucapra/diospyros#61]
For the generated kernel, the scalars.h import uses a relative path in the file. Recommend forcing the build to copy scalars.h into compile-out/include or something similar so that the compile output is self-contained.

#include <float.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <xtensa/sim.h>
#include <xtensa/tie/xt_pdxn.h>
#include <xtensa/tie/xt_timer.h>
#include <xtensa/xt_profiling.h>
#include "../../../../src/scalars.h" // scalars.h requires relative path -> would rather have #include <scalar.h> or <diosypros/scalar.h> or something similar.

**Comment by avanhatt** [comment]
Related to #55

**Comment by agent-lee** [comment]
Oh yeah good point. I'll comment over there.
