### ISSUE TITLE
Emit include header file to allow #include of kernel into codebase

### ISSUE THREAD

**Issue by agent-lee** [cucapra/diospyros#62]
For generated kernels, accompanying include header file for import is needed to allow it to get compiled into larger code bases. Quick fix might be to just emit a kernel.h and preprocessor.h file for now with just the signature definitions which can be picked up by a build system.

**Comment by avanhatt** [comment]
Good point! Just so I'm clear, what are you suggesting would be emitted in `preprocessor.h`? The C spec header?

**Comment by agent-lee** [comment]
Yep. Just the specification function header. Basically I need to cobble together a header file like this to import for other builds:
