### ISSUE TITLE
Partial PDX_SAV_MXF32_XP stores must be flushed to memory

### ISSUE THREAD

**Issue by agent-lee** [cucapra/diospyros#64]
The intrinsic that saves to memory works if filling all 16 bytes when called as such:
PDX_SAV_MXF32_XP(v_43, align_c_out, (xb_vecMxf32 *)c_out, 16);
However, when filling less than 16 bytes, it will cause the store to fail and not propagate. So for instance, invoking this instruction by itself will not actually propagate the store to the first word of the memory:
PDX_SAV_MXF32_XP(v_43, align_c_out, (xb_vecMxf32 *)c_out, 4);
The solution is to either add the following flush after the PDX_SAV_MXF32_XP instruction or in the case of writing one word, to just store to the pointer:
PDX_SAPOS_FP(align_c_out, (xb_vec4Mx8 *)c_out); // added after PDX_SAV_MXF32_XP
or
*c_out = <whatever value in v_43>; // just directly save value

Currently the compiler generated kernel does not flush the data out which causes it to produce partially incorrect results because values are not propagated.

**Comment by avanhatt** [comment]
Fixing now! Will directly write for one word, and otherwise flush if the final write is unaligned
