### ISSUE TITLE
Runtime validation failing for various matrix multiply configurations

### ISSUE THREAD

**Issue by agent-lee** [cucapra/diospyros#72]
After some initial results after running coverage over different matrix multiply dimensions, the following configurations appear to be failing validation. I think this may again be related to how we store the results back to memory but not sure. The failing cases appears to be super small dimensionality corner cases. The remaining results are still being generated.

Failing configurations:
input_rows, input_cols, output_cols
1, 1, 2
1, 2, 3
1, 1, 5
1, 1, 7
1, 2, 1
1, 2, 2, 
1, 2, 3
1, 3, 1
1, 3, 2
1, 3, 3
1, 4, 2
1, 6, 1

Repro from 1054f25:
- `eigen --kernel multiple --input_rows <input_rows> --input_cols <input_cols> --output_cols <output_cols>`
- Validation when running the test harness will throw a failure when validating the synthesized kernel against the specification

**Comment by avanhatt** [comment]
Fixed in several issues, the latest of which was https://github.com/cucapra/diospyros/commit/7ea35e7f8649aa53b1df3b080b21c53b098493d1
