### ISSUE TITLE
cdios: support local static array initialization 

### ISSUE THREAD

**Issue by avanhatt** [cucapra/diospyros#84]
In a point product kernel, we want to write:
```
float qvec[3] = {q_in[0], q_in[1], q_in[2]};
```
But currently need to write:
```
  float qvec[3];
  qvec[0] = q_in[0];
  qvec[1] = q_in[1];
  qvec[2] = q_in[2];
```

**Comment by JonathanDLTran** [comment]
I compared the master and branch directories's expected files and they look identical for all the tests, in particular the point-product test no longer has differences. Should I create a pull request?

**Comment by avanhatt** [comment]
@JonathanDLTran yes please to opening a pull request, thanks!
